name: 'Set up GitHub Actions caching for Turborepo'
description: 'Sets up Turborepo Remote Caching to work with GitHub Actions’ built-in cache. No Vercel account access tokens needed.'
author: 'Thai Pangsakulyanont'
branding:
  icon: cloud-lightning
  color: blue
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'post.js'
inputs:
  cache-prefix:
    description: 'Prefix for the cache key'
    required: false
    default: turbogha_
  host:
    description: 'Server listen host'
    required: false
    default: localhost
